use sqlx::{PgPool, Row};

/// Quote an identifier only when Postgres would not fold it to what we want.
fn quote(identifier: &str) -> String {
    let simple = !identifier.is_empty()
        && identifier
            .chars()
            .all(|c| c.is_ascii_lowercase() || c.is_ascii_digit() || c == '_')
        && !identifier.chars().next().is_some_and(|c| c.is_ascii_digit());
    if simple {
        identifier.to_string()
    } else {
        format!("\"{}\"", identifier.replace('"', "\"\""))
    }
}

/// Reconstruct `CREATE TABLE` DDL from the catalogs.
///
/// Postgres has no `SHOW CREATE TABLE`, so the statement is assembled from
/// `pg_attribute`, `pg_get_constraintdef`, and `pg_indexes`. It is meant to be
/// read and copied, not to round-trip every exotic table option.
pub async fn table_ddl(pool: &PgPool, schema: &str, table: &str) -> Result<String, String> {
    let relkind: Option<String> = sqlx::query_scalar(
        "SELECT c.relkind::text
         FROM pg_catalog.pg_class c
         JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace
         WHERE n.nspname = $1 AND c.relname = $2",
    )
    .bind(schema)
    .bind(table)
    .fetch_optional(pool)
    .await
    .map_err(|error| error.to_string())?;

    let relkind = relkind.ok_or_else(|| format!("'{schema}.{table}' was not found."))?;

    if relkind == "v" || relkind == "m" {
        return view_ddl(pool, schema, table, relkind == "m").await;
    }

    let qualified = format!("{}.{}", quote(schema), quote(table));
    let mut lines: Vec<String> = Vec::new();

    let columns = sqlx::query(
        "SELECT a.attname,
                pg_catalog.format_type(a.atttypid, a.atttypmod),
                a.attnotnull,
                pg_catalog.pg_get_expr(d.adbin, d.adrelid),
                a.attidentity::text,
                a.attgenerated::text
         FROM pg_catalog.pg_attribute a
         JOIN pg_catalog.pg_class c ON c.oid = a.attrelid
         JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace
         LEFT JOIN pg_catalog.pg_attrdef d
           ON d.adrelid = a.attrelid AND d.adnum = a.attnum
         WHERE n.nspname = $1 AND c.relname = $2
           AND a.attnum > 0 AND NOT a.attisdropped
         ORDER BY a.attnum",
    )
    .bind(schema)
    .bind(table)
    .fetch_all(pool)
    .await
    .map_err(|error| error.to_string())?;

    if columns.is_empty() {
        return Err(format!("'{schema}.{table}' has no readable columns."));
    }

    for row in &columns {
        let name: String = row.try_get(0).map_err(|error| error.to_string())?;
        let data_type: String = row.try_get(1).map_err(|error| error.to_string())?;
        let not_null: bool = row.try_get(2).unwrap_or(false);
        let default: Option<String> = row.try_get(3).ok().flatten();
        let identity: String = row.try_get(4).unwrap_or_default();
        let generated: String = row.try_get(5).unwrap_or_default();

        let mut line = format!("    {} {}", quote(&name), data_type);
        match identity.as_str() {
            "a" => line.push_str(" GENERATED ALWAYS AS IDENTITY"),
            "d" => line.push_str(" GENERATED BY DEFAULT AS IDENTITY"),
            _ => {
                if let Some(expression) = default {
                    if generated == "s" {
                        line.push_str(&format!(" GENERATED ALWAYS AS ({expression}) STORED"));
                    } else {
                        line.push_str(&format!(" DEFAULT {expression}"));
                    }
                }
            }
        }
        if not_null {
            line.push_str(" NOT NULL");
        }
        lines.push(line);
    }

    // Constraint definitions come straight from Postgres, so they are exact.
    let constraints = sqlx::query(
        "SELECT con.conname, pg_catalog.pg_get_constraintdef(con.oid)
         FROM pg_catalog.pg_constraint con
         JOIN pg_catalog.pg_class c ON c.oid = con.conrelid
         JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace
         WHERE n.nspname = $1 AND c.relname = $2
         ORDER BY CASE con.contype
                    WHEN 'p' THEN 0 WHEN 'u' THEN 1
                    WHEN 'c' THEN 2 ELSE 3
                  END,
                  con.conname",
    )
    .bind(schema)
    .bind(table)
    .fetch_all(pool)
    .await
    .map_err(|error| error.to_string())?;

    for row in &constraints {
        let name: String = row.try_get(0).map_err(|error| error.to_string())?;
        let definition: String = row.try_get(1).map_err(|error| error.to_string())?;
        lines.push(format!("    CONSTRAINT {} {}", quote(&name), definition));
    }

    let mut ddl = format!("CREATE TABLE {qualified} (\n{}\n);", lines.join(",\n"));

    // Indexes that merely back a constraint are already covered above.
    let indexes = sqlx::query(
        "SELECT i.indexdef
         FROM pg_catalog.pg_indexes i
         WHERE i.schemaname = $1 AND i.tablename = $2
           AND NOT EXISTS (
             SELECT 1
             FROM pg_catalog.pg_constraint con
             JOIN pg_catalog.pg_class ic ON ic.oid = con.conindid
             JOIN pg_catalog.pg_namespace icn ON icn.oid = ic.relnamespace
             WHERE icn.nspname = i.schemaname AND ic.relname = i.indexname
           )
         ORDER BY i.indexname",
    )
    .bind(schema)
    .bind(table)
    .fetch_all(pool)
    .await
    .map_err(|error| error.to_string())?;

    if !indexes.is_empty() {
        ddl.push('\n');
        for row in &indexes {
            let definition: String = row.try_get(0).unwrap_or_default();
            if !definition.is_empty() {
                ddl.push_str(&format!("\n{definition};"));
            }
        }
    }

    let comments = sqlx::query(
        "SELECT a.attname, pg_catalog.col_description(c.oid, a.attnum)
         FROM pg_catalog.pg_attribute a
         JOIN pg_catalog.pg_class c ON c.oid = a.attrelid
         JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace
         WHERE n.nspname = $1 AND c.relname = $2
           AND a.attnum > 0 AND NOT a.attisdropped
           AND pg_catalog.col_description(c.oid, a.attnum) IS NOT NULL
         ORDER BY a.attnum",
    )
    .bind(schema)
    .bind(table)
    .fetch_all(pool)
    .await
    .map_err(|error| error.to_string())?;

    if !comments.is_empty() {
        ddl.push('\n');
        for row in &comments {
            let column: String = row.try_get(0).unwrap_or_default();
            let comment: String = row.try_get(1).unwrap_or_default();
            ddl.push_str(&format!(
                "\nCOMMENT ON COLUMN {qualified}.{} IS '{}';",
                quote(&column),
                comment.replace('\'', "''")
            ));
        }
    }

    Ok(ddl)
}

async fn view_ddl(
    pool: &PgPool,
    schema: &str,
    view: &str,
    materialized: bool,
) -> Result<String, String> {
    let definition: String = sqlx::query_scalar(
        "SELECT pg_catalog.pg_get_viewdef(c.oid, true)
         FROM pg_catalog.pg_class c
         JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace
         WHERE n.nspname = $1 AND c.relname = $2",
    )
    .bind(schema)
    .bind(view)
    .fetch_one(pool)
    .await
    .map_err(|error| error.to_string())?;

    let keyword = if materialized {
        "CREATE MATERIALIZED VIEW"
    } else {
        "CREATE OR REPLACE VIEW"
    };
    Ok(format!(
        "{keyword} {}.{} AS\n{}",
        quote(schema),
        quote(view),
        definition.trim()
    ))
}

#[cfg(test)]
mod tests {
    use super::quote;

    #[test]
    fn leaves_simple_identifiers_bare() {
        assert_eq!(quote("users"), "users");
        assert_eq!(quote("user_id_2"), "user_id_2");
    }

    #[test]
    fn quotes_identifiers_needing_it() {
        assert_eq!(quote("Users"), "\"Users\"");
        assert_eq!(quote("user name"), "\"user name\"");
        assert_eq!(quote("2fast"), "\"2fast\"");
    }

    #[test]
    fn escapes_embedded_quotes() {
        assert_eq!(quote("we\"ird"), "\"we\"\"ird\"");
    }
}
